const products = [
  {
    title: "Pantalón de mezclilla",
    description: "Pantalón cómodo y resistente de mezclilla.",
    price: 28.99,
    code: "P001",
    category: "pantalones",
    stock: 10,
    thumbnail: "https://example.com/pants.jpg",
  },
  {
    title: "Remera de algodón",
    description: "Remera de algodón suave y cómoda.",
    price: 12.99,
    code: "P002",
    category: "remeras",
    stock: 20,
    thumbnail: "https://example.com/shirt.jpg",
  },
  {
    title: "Zapatillas deportivas",
    description: "Zapatillas cómodas y duraderas para hacer deporte.",
    price: 65.99,
    code: "P003",
    category: "zapatos",
    stock: 5,
    thumbnail: "https://example.com/sneakers.jpg",
  },
  {
    title: "Camisa de vestir",
    description: "Camisa de vestir elegante para ocasiones especiales.",
    price: 42.99,
    code: "P004",
    category: "camisas",
    stock: 8,
    thumbnail: "https://example.com/dress-shirt.jpg",
  },
  {
    title: "Jeans ajustados",
    description: "Jeans ajustados y modernos para cualquier ocasión.",
    price: 34.99,
    code: "P005",
    category: "pantalones",
    stock: 15,
    thumbnail: "https://example.com/skinny-jeans.jpg",
  },
  {
    title: "Sweater de lana",
    description: "Sweater de lana suave y cálido para los días fríos.",
    price: 24.99,
    code: "P006",
    category: "remeras",
    stock: 12,
    thumbnail: "https://example.com/sweater.jpg",
  },
  {
    title: "Botas de cuero",
    description: "Botas de cuero resistentes para cualquier clima.",
    price: 89.99,
    code: "P007",
    category: "zapatos",
    stock: 3,
    thumbnail: "https://example.com/boots.jpg",
  },
  {
    title: "Camisa casual",
    description: "Camisa casual y cómoda para cualquier ocasión.",
    price: 19.99,
    code: "P008",
    category: "camisas",
    stock: 18,
    thumbnail: "https://example.com/casual-shirt.jpg",
  },
  {
    title: "Pantalón chino",
    description: "Pantalón chino de tela suave y fresca.",
    price: 32.99,
    code: "P009",
    category: "pantalones",
    stock: 7,
    thumbnail: "https://example.com/chinos.jpg",
  },
  {
    title: "Remera sin mangas",
    description: "Remera sin mangas fresca y cómoda para el verano.",
    price: 9.99,
    code: "P010",
    category: "remeras",
    stock: 25,
    thumbnail: "https://example.com/tank-top.jpg",
  },
  {
    title: "Zapatillas urbanas",
    description: "Zapatillas urbanas modernas y cómodas.",
    price: 59.99,
    code: "P011",
    category: "zapatos",
    stock: 6,
    thumbnail: "https://example.com/urban-sneakers.jpg",
  },
  {
    title: "Camisa de denim",
    description: "Camisa de denim resistente y moderna.",
    price: 37.99,
    code: "P012",
    category: "camisas",
    stock: 9,
    thumbnail: "https://example.com/denim-shirt.jpg",
  },
  {
    title: "Pantalón de vestir",
    description: "Pantalón de vestir elegante y cómodo.",
    price: 49.99,
    code: "P013",
    category: "pantalones",
    stock: 11,
    thumbnail: "https://example.com/dress-pants.jpg",
  },
  {
    title: "Remera estampada",
    description: "Remera estampada con diseño moderno y original.",
    price: 14.99,
    code: "P014",
    category: "remeras",
    stock: 22,
    thumbnail: "https://example.com/printed-shirt.jpg",
  },
  {
    title: "Zapatillas de running",
    description: "Zapatillas de running cómodas y duraderas.",
    price: 79.99,
    code: "P015",
    category: "zapatos",
    stock: 4,
    thumbnail: "https://example.com/running-shoes.jpg",
  },
  {
    title: "Camisa de lino",
    description: "Camisa de lino fresca y ligera para el verano.",
    price: 29.99,
    code: "P016",
    category: "camisas",
    stock: 14,
    thumbnail: "https://example.com/linen-shirt.jpg",
  },
  {
    title: "Pantalón cargo",
    description: "Pantalón cargo resistente y práctico.",
    price: 45.99,
    code: "P017",
    category: "pantalones",
    stock: 8,
    thumbnail: "https://example.com/cargo-pants.jpg",
  },
  {
    title: "Remera de manga larga",
    description: "Remera de manga larga suave y cómoda.",
    price: 17.99,
    code: "P018",
    category: "remeras",
    stock: 18,
    thumbnail: "https://example.com/long-sleeve-shirt.jpg",
  },
  {
    title: "Zapatillas de cuero",
    description: "Zapatillas de cuero elegantes y cómodas.",
    price: 69.99,
    code: "P019",
    category: "zapatos",
    stock: 5,
    thumbnail: "https://example.com/leather-sneakers.jpg",
  },
  {
    title: "Camisa a cuadros",
    description: "Camisa a cuadros de estilo leñador.",
    price: 33.99,
    code: "P020",
    category: "camisas",
    stock: 10,
    thumbnail: "https://example.com/flannel-shirt.jpg",
  },
  {
    title: "Pantalón chino",
    description: "Pantalón chino clásico y versátil.",
    price: 39.99,
    code: "P021",
    category: "pantalones",
    stock: 13,
    thumbnail: "https://example.com/chino-pants.jpg",
  },
  {
    title: "Remera de algodón",
    description: "Remera de algodón suave y cómoda.",
    price: 12.99,
    code: "P022",
    category: "remeras",
    stock: 30,
    thumbnail: "https://example.com/cotton-shirt.jpg",
  },
  {
    title: "Botas de cuero",
    description: "Botas de cuero resistentes y duraderas.",
    price: 99.99,
    code: "P023",
    category: "zapatos",
    stock: 3,
    thumbnail: "https://example.com/leather-boots.jpg",
  },
  {
    title: "Camisa de lana",
    description: "Camisa de lana abrigada y cómoda.",
    price: 47.99,
    code: "P024",
    category: "camisas",
    stock: 8,
    thumbnail: "https://example.com/wool-shirt.jpg",
  },
  {
    title: "Pantalón cargo corto",
    description: "Pantalón cargo corto resistente y práctico.",
    price: 29.99,
    code: "P025",
    category: "pantalones",
    stock: 15,
    thumbnail: "https://example.com/short-cargo-pants.jpg",
  },
  {
    title: "Remera estampada de manga larga",
    description: "Remera estampada de manga larga con diseño moderno.",
    price: 19.99,
    code: "P026",
    category: "remeras",
    stock: 20,
    thumbnail: "https://example.com/printed-long-sleeve-shirt.jpg",
  },
  {
    title: "Zapatillas deportivas",
    description: "Zapatillas deportivas cómodas y resistentes.",
    price: 84.99,
    code: "P027",
    category: "zapatos",
    stock: 7,
    thumbnail: "https://example.com/sport-sneakers.jpg",
  },
  {
    title: "Camisa de franela",
    description: "Camisa de franela abrigada y cómoda.",
    price: 45.99,
    code: "P028",
    category: "camisas",
    stock: 11,
    thumbnail: "https://example.com/flannel-shirt-2.jpg",
  },
  {
    title: "Pantalón jogger",
    description: "Pantalón jogger de estilo urbano y cómodo.",
    price: 49.99,
    code: "P029",
    category: "pantalones",
    stock: 17,
    thumbnail: "https://example.com/jogger-pants.jpg",
  },
  {
    title: "Remera básica de algodón",
    description: "Remera básica de algodón suave y cómoda.",
    price: 9.99,
    code: "P030",
    category: "remeras",
    stock: 40,
    thumbnail: "https://example.com/basic-cotton-shirt.jpg",
  },
  {
    title: "Zapatillas de running",
    description: "Zapatillas de running con buena amortiguación.",
    price: 89.99,
    code: "P031",
    category: "zapatos",
    stock: 6,
    thumbnail: "https://example.com/running-sneakers.jpg",
  },
  {
    title: "Camisa de cuadros",
    description: "Camisa de cuadros con diseño clásico.",
    price: 34.99,
    code: "P032",
    category: "camisas",
    stock: 9,
    thumbnail: "https://example.com/checkered-shirt.jpg",
  },
  {
    title: "Pantalón de lino",
    description: "Pantalón de lino fresco y cómodo.",
    price: 59.99,
    code: "P033",
    category: "pantalones",
    stock: 12,
    thumbnail: "https://example.com/linen-pants.jpg",
  },
  {
    title: "Remera estampada de manga corta",
    description: "Remera estampada de manga corta con diseño moderno.",
    price: 14.99,
    code: "P034",
    category: "remeras",
    stock: 25,
    thumbnail: "https://example.com/printed-short-sleeve-shirt.jpg",
  },
  {
    title: "Botas de montaña",
    description: "Botas de montaña resistentes y cómodas.",
    price: 119.99,
    code: "P035",
    category: "zapatos",
    stock: 4,
    thumbnail: "https://example.com/mountain-boots.jpg",
  },
  {
    title: "Camisa de denim",
    description: "Camisa de denim resistente y duradera.",
    price: 39.99,
    code: "P036",
    category: "camisas",
    stock: 7,
    thumbnail: "https://example.com/denim-shirt.jpg",
  },
  {
    title: "Pantalón cargo",
    description: "Pantalón cargo resistente y con muchos bolsillos.",
    price: 54.99,
    code: "P037",
    category: "pantalones",
    stock: 15,
    thumbnail: "https://example.com/cargo-pants.jpg",
  },
  {
    title: "Remera con estampado de bandas de rock",
    description: "Remera con estampado de bandas de rock clásicas.",
    price: 19.99,
    code: "P038",
    category: "remeras",
    stock: 20,
    thumbnail: "https://example.com/rock-band-tshirt.jpg",
  },
  {
    title: "Zapatillas de skate",
    description: "Zapatillas de skate resistentes y con buen agarre.",
    price: 69.99,
    code: "P039",
    category: "zapatos",
    stock: 8,
    thumbnail: "https://example.com/skate-shoes.jpg",
  },
  {
    title: "Camisa de algodón",
    description: "Camisa de algodón suave y cómoda.",
    price: 29.99,
    code: "P040",
    category: "camisas",
    stock: 10,
    thumbnail: "https://example.com/cotton-shirt.jpg",
  },
  {
    title: "Pantalón chino",
    description: "Pantalón chino clásico y elegante.",
    price: 49.99,
    code: "P041",
    category: "pantalones",
    stock: 14,
    thumbnail: "https://example.com/chino-pants.jpg",
  },
  {
    title: "Remera de tirantes",
    description: "Remera de tirantes suave y cómoda.",
    price: 7.99,
    code: "P042",
    category: "remeras",
    stock: 35,
    thumbnail: "https://example.com/tank-top.jpg",
  },
  {
    title: "Botas de cuero",
    description: "Botas de cuero elegantes y duraderas.",
    price: 99.99,
    code: "P043",
    category: "zapatos",
    stock: 5,
    thumbnail: "https://example.com/leather-boots.jpg",
  },
  {
    title: "Camisa estampada",
    description: "Camisa estampada con diseño original.",
    price: 42.99,
    code: "P044",
    category: "camisas",
    stock: 8,
    thumbnail: "https://example.com/printed-shirt.jpg",
  },
  {
    title: "Pantalón de cuero",
    description: "Pantalón de cuero resistente y elegante.",
    price: 149.99,
    code: "P045",
    category: "pantalones",
    stock: 4,
    thumbnail: "https://example.com/leather-pants.jpg",
  },
  {
    title: "Remera de manga larga",
    description: "Remera de manga larga suave y cómoda.",
    price: 12.99,
    code: "P046",
    category: "remeras",
    stock: 50,
    thumbnail: "https://example.com/images/remera_manga_larga.jpg",
  },
  {
    title: "Jean Slim Fit",
    description: "Jean Slim Fit de alta calidad y cómodo",
    price: 35.99,
    code: "P047",
    category: "pantalones",
    stock: 30,
    thumbnail: "https://example.com/images/jean_slim_fit.jpg",
  },
  {
    title: "Zapatillas deportivas",
    description: "Zapatillas deportivas con excelente amortiguación",
    price: 59.99,
    code: "P048",
    category: "zapatos",
    stock: 20,
    thumbnail: "https://example.com/images/zapatillas_deportivas.jpg",
  },
  {
    title: "Camisa de cuadros",
    description: "Camisa de cuadros en algodón suave",
    price: 25.99,
    code: "P049",
    category: "camisas",
    stock: 40,
    thumbnail: "https://example.com/images/camisa_cuadros.jpg",
  },
  {
    title: "Pantalón de chándal",
    description: "Pantalón de chándal de algodón suave y cómodo",
    price: 19.99,
    code: "P050",
    category: "pantalones",
    stock: 25,
    thumbnail: "https://example.com/images/pantalon_chandal.jpg",
  },
];

export default products;
